# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
        server-id: codingsoup
        server-username: codingsoup
        server-password: l47xgltiqoizkz5xznsh2rdnpl2mkgtmlszfqcr3gsyugj57bwua
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload sbom.json
      uses: actions/upload-artifact@v2
      with:
        name: sbom.json
        path: target/artifact
        
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.ARTIFACTS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
